openapi: 3.0.3
info:
  title: Restaurant BFF OpenAPI document
  version: 0.0.1
paths:
  # USER API
  /user/{userId}:
    get:
      summary: Get User By id.
      description: Retrieves a user by passing an id.
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "user got."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
    put:
      summary: Edit User By id.
      description: Edit a user by passing an id.
      operationId: editUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        "200":
          description: "user edited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
    delete:
      summary: Delete User By id.
      description: Delete a user by passing an id.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "user deleted."
          content:
            application/json:
              schema:
                type: string
  # RESTAURANT API
  /restaurant/{restaurantId}:
    get:
      summary: Get Restaurant By id.
      description: Retrieves a restaurant by passing an id.
      operationId: getRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Restaurant got."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
    put:
      summary: Edit Restaurant By id.
      description: Edit restaurant by passing an id.
      operationId: editRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantDTO"
      responses:
        "200":
          description: "Restaurant edited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
    delete:
      summary: Delete Restaurant By id.
      description: Retrieves the deleted restaurant.
      operationId: deleteRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Restaurant deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
  /restaurant:
    post:
      summary: Create Restaurant.
      description: Create Restaurant.
      operationId: createRestaurant
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RestaurantDTO"
      responses:
        "200":
          description: "Restaurant created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
    get:
      summary: Get All Restaurants.
      description: Get All Restaurants.
      operationId: getAllRestaurants
      responses:
        "200":
          description: "Restaurants got."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantDTO"
  /restaurant/add/employee/{restaurantId}/{employeeId}:
    put:
      summary: Add Employee to Restaurant.
      description: Add Employee to Restaurant.
      operationId: addEmployee
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Restaurant with employee added."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
  /restaurant/remove/employee/{restaurantId}/{employeeId}:
    put:
      summary: Remove Employee from Restaurant.
      description: Remove Employee from Restaurant.
      operationId: removeEmployee
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Restaurant with employee removed."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RestaurantDTO"
  /restaurant/{lat}/{lng}:
    get:
      summary: Persist Restaurants Near the Coordinate.
      description: Retrieves a restaurant list persisted after passing a latitude and a longitude.
      operationId: persistRestaurantsNearTheCoordinate
      parameters:
        - name: lat
          in: path
          required: true
          schema:
            type: string
        - name: lng
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Restaurant List Near the coordinate."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RestaurantDTO"
  #EMPLOYEE API
  /employee/{employeeId}:
    get:
      summary: Get Employee By id.
      description: Retrieves an employee by passing an id.
      operationId: getEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Employee got."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"
    put:
      summary: Edit Employee By id.
      description: Edit employee by passing an id.
      operationId: editEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeDTO"
      responses:
        "200":
          description: "Restaurant edited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"
    delete:
      summary: Delete Employee By id.
      description: Retrieves the deleted employee.
      operationId: deleteEmployee
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Employee deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"
  /employee:
    post:
      summary: Create Employee.
      description: Create Employee.
      operationId: createEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeDTO"
      responses:
        "200":
          description: "Employee created."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"
    get:
      summary: Get All Employees.
      description: Get All Employees.
      operationId: getAllEmployees
      responses:
        "200":
          description: "Employees got."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmployeeDTO"
  /employee/add/restaurant/{employeeId}/{restaurantId}:
    put:
      summary: Add Restaurant to Employee.
      description: Add Restaurant to Employee.
      operationId: addRestaurant
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Employee with restaurant added."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"
  /employee/remove/restaurant/{employeeId}/{restaurantId}:
    put:
      summary: Remove Restaurant from Employee.
      description: Remove Restaurant from Employee.
      operationId: removeRestaurant
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Employee with restaurant removed."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeDTO"

servers:
  - url: http://localhost:8080/api

components:
  schemas:
    AddressDTO:
      type: object
      properties:
        name:
          type: string
        postalCode:
          type: string
        city:
          type: string
        country:
          type: string
    CoordinateDTO:
      type: object
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    LocationDTO:
      type: object
      properties:
        address:
          $ref: "#/components/schemas/AddressDTO"
        locationCoordinate:
          $ref: "#/components/schemas/CoordinateDTO"
    MenuDTO:
      type: object
      properties:
        language:
          type: string
        uid:
          type: string
    ScheduleType:
      type: string
      enum:
        - PARTTIME
        - FULLTIME
        - INTERNSHIP
    EmployeeDTO:
      type: object
      properties:
        uid:
          type: string
        role:
          type: string
        restaurantList:
          type: setOfRestaurantDTO
        schedule:
          $ref: "#/components/schemas/ScheduleRoutineDTO"
    RestaurantDTO:
      type: object
      properties:
        uid:
          type: string
        hereId:
          type: string
        name:
          type: string
        location:
          $ref: "#/components/schemas/LocationDTO"
        capacity:
          type: integer
        menu:
          $ref: "#/components/schemas/MenuDTO"
        schedule:
          $ref: "#/components/schemas/ScheduleRoutineDTO"
        employeeList:
          type: setOfEmployeeDTO
    ScheduleRoutineDTO:
      type: object
      properties:
        daysScheduleMap:
          additionalProperties:
            type: daysScheduleMap
    ScheduleTimeDTO:
      type: object
      properties:
        startTime:
          type: localTime
        endTime:
          type: localTime
    UserDTO:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
