spring:
  application:
    name: pep-restaurant-ms-bff
  liquibase:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: dev
  logging:
    level:
      org:
        springframework:
          security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /pep/restaurant/bff
keycloak:
  realm: ${KEYCLOAK_REALM:peprestaurant}
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081/auth}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:peprestaurant}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:7daab491-6470-4db1-9caa-183af7d78e8d}
  use-resource-role-mappings: true

application:
  keycloak:
    serverUrl: ${KEYCLOAK_SERVER_URL:http://localhost:8081/auth}
    realm: ${KEYCLOAK_REALM:peprestaurant}
    username: ${KEYCLOAK_USER:pepuser}
    password: ${KEYCLOAK_PASSWORD:1234}
    clientId: ${KEYCLOAK_CLIENT_ID:peprestaurant}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET:7daab491-6470-4db1-9caa-183af7d78e8d}
  msManager:
    url: ${PEP_RESTAURANT_MS_MANAGER_URL:http://localhost:8082/pep/restaurant/manager}
