spring:
  application:
    name: pep-restaurant-ms-bff
  liquibase:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /pep/restaurant/bff

application:
  keycloak:
    serverUrl: ${KEYCLOAK_SERVER_URL:http://localhost:8081/auth}
    realm: ${KEYCLOAK_REALM:peprestaurant}
    username: ${KEYCLOAK_USERNAME:pepuser}
    password: ${KEYCLOAK_PASSWORD:1234}
    clientId: ${KEYCLOAK_CLIENT_ID:peprestaurant}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET:afb48af0-a6b9-44b7-ba43-328f3e5a6555}
  msManager:
    url: http://localhost:8082/pep/restaurant/manager
